### ISSUE TITLE
VLSub crashes when it calculates hash

### ISSUE THREAD

**Issue by sebfindling** [exebetche/vlsub#144] opened 2016-10-30 03:22 UTC
I'm trying to fetch subtitles for a movie and when I click the button it shows the progress bar but it hangs there, not showing anything and then it shows a window about VLSub not responding.

I get the following debug. Apparently it's connecting to the server and calculating the hash, but nothing happens.

```
lua debug: [VLSub] file info Mr Robot S02E01 eps2 0 unm4sk-pt1 tc 720p WEB-DL x264-[MULVAcoded] Mr.Robot.S02E01.eps2.0_unm4sk-pt1.tc.720p.WEB-DL.x264-[MULVAcoded].mkv D:/sdelv/Downloads/Mr.Robot.Season.2.Complete.720p.WEB-DL.EN-SUB.x264-[MULVAcoded]/ mkv true false Mr.Robot.S02E01.eps2.0_unm4sk-pt1.tc.720p.WEB-DL.x264-[MULVAcoded] D:/sdelv/Downloads/Mr.Robot.Season.2.Complete.720p.WEB-DL.EN-SUB.x264-[MULVAcoded]/Mr.Robot.S02E01.eps2.0_unm4sk-pt1.tc.720p.WEB-DL.x264-[MULVAcoded].mkv file 1477004581 1477004581 0 33206 1477005031 235940536 file 0 file:///D:/sdelv/Downloads/Mr.Robot.Season.2.Complete.720p.WEB-DL.EN-SUB.x264-%5BMULVAcoded%5D/Mr.Robot.S02E01.eps2.0_unm4sk-pt1.tc.720p.WEB-DL.x264-%5BMULVAcoded%5D.mkv
lua debug: [VLSub] Read hash data from file
lua debug: [VLSub] Video hash: 9b93ec6ee92aff57
lua debug: [VLSub] Video bytesize: 235940536
core debug: net: connecting to api.opensubtitles.org port 80
core debug: connection succeeded (socket = 2528)
```

**Comment by opensubtitles** [comment] 2016-10-31 04:26
duplicate of https://github.com/exebetche/vlsub/issues/143

**Closed** 2016-11-04 20:47 UTC

**Comment by exebetche** [comment] 2016-11-05 12:22
Fixed
